let name = prompt("Ismingizni kiriting")
let surname = prompt("Familiyangizni kiriting")
let age = prompt("Yoshingizni kiriting")
let hobbi = prompt("Yoqtirgan faningizni yozing")
let residential_address = prompt("Yashash manzilingizni kiriting") 
console.log("Name =" + name)
console.log("Surname =" + surname)
console.log("Age =" + age)
console.log("Hobbi =" + hobbi)
console.log("Residential address =" + residential_address)
alert("Malumotingiz uchun rahmat!")